OIM2022/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
]

homepage/urls.py
from django.urls import path

from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('aboutus/', views.about, name='about'),
    path('competitions/', views.competitions, name='competitions'),
    path('booklets/', views.booklets, name='booklets'),
    path('timeline/<str:competition>/', views.timeline, name='timeline'),
    path('gallery/', views.gallery, name='gallery'),
    path('pagenotavailable/', views.pagenotavailable, name='pagenotavailable'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, "homepage.html")

def about(request):
    return render(request, 'about.html')

def competitions(request):
    return render(request, 'competitions.html')

def booklets(request):
    return render(request, 'booklets.html')

def timeline(request, competition):
    url = ''
    if competition == "debat" :
        url = 'timeline_debat.html'
    elif competition == "quiz":
        url = 'timeline_quiz.html'
    elif competition == "essay":
        url = 'timeline_essay.html'
    elif competition == "poster":
        url = 'timeline_poster.html'
    elif competition == "pkmai":
        url = 'timeline_pkmai.html'
    elif competition == "pkmvgk":
        url = 'timeline_pkmvgk.html'
    elif competition == "pkmgft":
        url = 'timeline_pkmgft.html'
    elif competition == "pkmk":
        url = 'timeline_pkmk.html'
    elif competition == "pkmkc":
        url = 'timeline_pkmkc.html'
    elif competition == "pkmpi":
        url = 'timeline_pkmpi.html'
    elif competition == "pkmpm":
        url = 'timeline_pkmpm.html'
    elif competition == "pkmre":
        url = 'timeline_pkmre.html'
    elif competition == "pkmrsh":
        url = 'timeline_pkmrsh.html'
    elif competition == "pkmki":
        url = 'timeline_pkmki.html'
    elif competition == "all":
        url = 'timeline.html'
    else :
        url = 'error/404.html'
    return render(request, url)

def handler404(request, exception):
    return render(request, 'error/404.html',status=404)

def handler500(request):
    return render(request, 'error/500.html', status=500)

def gallery(request):
    return render(request, 'gallery.html')

def pagenotavailable(request):
    return render(request, '503.html')   

homepage/templates/navbar.html
{% load static %}
<script src="{% static 'javascript/navbar.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<nav>
	<a class="logo_mobile" href="{% url 'homepage:homepage' %}"><img src="/static/images/others/Logo.png" height="30px" alt="Logo OIM 2022"></a>
	<div class="navi">
		<div class="hamburger">
			<img class="dropdown" src="{% static 'images/others/dropdown.svg' %}" height="15px" alt="Dropdown">
		</div>
		<div class="container" style="height: 100%;">
			<div class="row" style="height: inherit;">
				<div class="col-3 onlypc">
					<a 
						class="logo_pc" 
						href="{% url 'homepage:homepage' %}"
					>
						<img height="60px" src="/static/images/others/Logo.png" alt="Logo OIM 2022">
					</a>
				</div>
				<div class="col" style="padding-right: 13px;">
					<ul class="nav-links" >
						<li>
							<a 
								href="{% url 'homepage:about' %}" 
								style="
									color: #0e1738;
								"
							>	
								About
							</a>
						</li>
						<li>
							<a 
								href="{% url 'homepage:competitions' %}" 
								style="
									color: #0e1738;
								"
							>	
								Competitions
							</a>
						</li>
						<li>
							<a 
								href="{% url 'homepage:timeline' 'all' %}" 
								style="
									color: #0e1738;
								"
							>	
								Timeline
							</a>
						</li>
						<li>
							<a 
								onclick="uploadon('upload_foreground_daftar')" 
								style="
									color: #0e1738;
									"
							>
								Booklets
							</a>
						</li>
						<div class="onlypc" style="width: 15px;"></div>
						<li>
							<a 
								class="mybutton"
								href="https://docs.google.com/forms/d/1YSUMXVDt_n_AtYun7EG5dOWw7SowM-r1riwklC7Dn2I/viewform?edit_requested=true"
								style="
									background: aqua;
									color: black !important;
									"
							>
								Daftar
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
        <!-- Farizio was here -->
	</div>
</nav>

homepage/templates/overlay_pkmai.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/overlay.css' %}">
<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_sub_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Thu, Sept 23 2021 <br>08:30 WIB – 18:00 WIB</p>
                <div class="alamat">
                    <!-- <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p> -->
                    <!-- <div style="width: 5px"></div> -->
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a class="mybutton aqua" href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform?usp=sf_link" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_sub_open_1">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Sep 26 2022 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a class="mybutton aqua" href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform?usp=sf_link" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_sub_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Thu, Oct 14 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform?usp=sf_link" class="mybutton aqua" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">
            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_video_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Video Upload Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Oct 04 2021 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform?usp=sf_link" class="mybutton aqua" id="overlay_linklomba">Upload Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_video_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Video Upload Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Sun, Oct 24 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform?usp=sf_link" class="mybutton aqua" id="overlay_linklomba">Upload Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_proposal_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: aqua;" >Proposal Grading Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Oct 18 2021 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>

                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>
 
<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_proposal_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Proposal Grading Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Sun, Nov 14 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>

                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

homepage/templates/overlay_pkmki.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/overlay.css' %}">
<div style="color: #0e1738;" class="fore overlay_foreground pkmki" id="pkmki_sub_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM KI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmki' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM KI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Thu, Sept 23 2021 <br>08:30 WIB – 18:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform" class="mybutton aqua" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmki" id="pkmki_sub_open_1">
    <div class="container"> 
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM KI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmki' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM KI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Sep 26 2022 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform" class="mybutton aqua" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmki" id="pkmki_sub_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM KI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmki' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM KI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Thu, Oct 14 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform" class="mybutton aqua" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmki" id="pkmki_video_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM KI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Video Upload Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmki' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM KI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Oct 04 2021 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform" class="mybutton aqua" id="overlay_linklomba">Upload Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div  style="color: #0e1738;" class="fore overlay_foreground pkmki" id="pkmki_video_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM KI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Video Upload Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmki' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM KI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Sun, Oct 24 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSc3FkFeaKoEQKNlDkda3_iYV_371D5jkNzSM771mz-Uv7X3Rw/viewform"class="mybutton aqua" id="overlay_linklomba">Upload Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div  style="color: #0e1738;" class="fore overlay_foreground pkmki" id="pkmki_proposal_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM KI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Proposal Grading Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmki' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM KI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Oct 18 2021 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>

                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmki" id="pkmki_proposal_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM KI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Proposal Grading Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmki' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM KI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Sun, Nov 14 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>

                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmki" id="pkmki_presentation">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM KI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Online Presentation</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmki' %}" id="overlay_viewnamalomba" class="loading" style="color:aqua">View All PKM KI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Nov 08 2021 <br>08:00 WIB - 17:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Zoom</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="{% url 'homepage:pagenotavailable' %}" class="mybutton aqua" id="overlay_linklomba">Watch Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>